---
swagger: "2.0"
info:
  description: "#### Echos back every URL, method, parameter and header\nFeel free\
    \ to make a path or an operation and use **Try Operation** to test it. The echo\
    \ server will\nrender back everything.\n"
  version: "1.0.0"
  title: "Simple Echo API (echo.coding4fun.rocks)"
host: "localhost:8080"
basePath: "/echo"
schemes:
- "http"
paths:
  /:
    get:
      operationId: "rootGET"
      parameters: []
      responses:
        200:
          description: "Echo GET"
      x-swagger-router-controller: "Default"
    post:
      operationId: "rootPOST"
      parameters:
      - name: "name"
        in: "formData"
        description: "name"
        required: false
        type: "string"
      - name: "year"
        in: "formData"
        description: "year"
        required: false
        type: "string"
      responses:
        200:
          description: "Echo POST"
      x-swagger-router-controller: "Default"
definitions: {}
